# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-08-29 16:32
from __future__ import unicode_literals

from django.db import migrations
import datetime


def copy_datetime_to_day(apps, schema_editor):
    Menu = apps.get_model('menu', 'Menu')
    for menu in Menu.objects.all():
        menu.expiration_date = datetime.date(
            year=menu.expiration_datetime.year,
            month=menu.expiration_datetime.month,
            day=menu.expiration_datetime.day
        )
        print(menu.expiration_date)
        menu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20190829_0929'),
    ]

    operations = [
        migrations.RunPython(copy_datetime_to_day)
    ]
