# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-08-29 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_copy_datetime_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='expiration_datetime',
        ),
    ]
